version: '3'

services:
  reverse-proxy:
    image: traefik:1.7
    command: --api --docker
    ports:
      - "81:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  isotope-server:
    image: marcnuri/isotope:server-latest
    ports:
      - "9010:9010"
    labels:
      - traefik.backend=isotope-server
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  isotope-client:
    image: marcnuri/isotope:client-latest
    ports:
      - "8081:80"
    labels:
      - traefik.backend=isotope-client
      - "traefik.frontend.rule=PathPrefixStrip:/"
